ungrouped:
  hosts:
    # TODO
load_balancer:
  hosts:
    localhost:
      ansible_host: 0.0.0.0
      ansible_connection: local 
      ansible_user: root

app_group:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2223
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2224
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2225