all:
  hosts:
    loadbalancer:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2222
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2223
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2224
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 2225

app_group:
  hosts:
    loadbalancer:
    managedhost-app-1:
    managedhost-app-2:
    managedhost-app-3: